release:
  stage: release
  image: python:3.11
  script:
    - "apt-get update && apt-get install -y git curl jq"
    - "pip install --upgrade pip"

    # Get current version from __init__.py
    - "VERSION=$(grep -Po \"(?<=__version__ = ')[^']+\" ./$CI_PROJECT_NAME/__init__.py)"
    - "echo \"Current version: $VERSION\""
    - "echo $VERSION > version.txt"

    # Fetch all tags
    - "git fetch --tags"
    - "TAG_EXISTS=$(git tag -l \"$VERSION\")"

    # Check if tag exists and bump version if needed
    - >
      if [ "$TAG_EXISTS" ]; then
        echo "Version $VERSION already tagged, bumping patch...";
        IFS="." read -r MAJOR MINOR PATCH <<< "$VERSION";
        PATCH=$((PATCH + 1));
        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}";
        echo "New version: $NEW_VERSION";
        echo "$NEW_VERSION" > version.txt;
        sed -i "s/__version__ = '$VERSION'/__version__ = '$NEW_VERSION'/" ./$CI_PROJECT_NAME/__init__.py;
        git config user.name "krunal-sigzen";
        git config user.email "krunal.p@sigzen.com";
        git commit -am "Bump version to $NEW_VERSION";
        git remote set-url origin http://sigzen:$GITLAB_TOKEN@192.168.1.51/Sigzen-Team/forward_contract.git
        git push origin HEAD:master;
      fi

    # Read the final version
    - "VERSION=$(cat version.txt)"
    - "echo Final version: $VERSION"

    # Create and push tag
    - "git tag $VERSION"
    - "git push origin $VERSION"

    # Get previous tag for changelog comparison
    - "PREV_TAG=$(git tag --sort=-creatordate | grep -v \"$VERSION\" | head -n 1)"
    - "echo \"Previous tag: $PREV_TAG\""

    # Build changelog comparison URL
    - "CHANGELOG_URL=\"http://192.168.1.51/$CI_PROJECT_PATH/-/compare/$PREV_TAG...$VERSION\""
    - "echo \"CHANGELOG_URL=$CHANGELOG_URL\""

    # Get commit messages between tags
    - "COMMIT_MESSAGES=$(git log --pretty=format:\"- %s\" \"$PREV_TAG..$VERSION\")"
    - "echo \"COMMIT_MESSAGES=$COMMIT_MESSAGES\""

    # Create release via GitLab API
    - >
      curl --request POST "http://192.168.1.51/api/v4/projects/${CI_PROJECT_ID}/releases"
      --header "PRIVATE-TOKEN: $GITLAB_TOKEN"
      --header "Content-Type: application/json"
      --data "{\"name\": \"$VERSION\", \"tag_name\": \"$VERSION\", \"description\": \"### Changes in this release:\n$COMMIT_MESSAGES\n\n[Changelog]($CHANGELOG_URL)\"}"
  only:
    - master
